#!/bin/bash

#1  Ստեղծել կամայական արժեքով փոփոխական՝ str: Ցուցադրել հետեւյալ հրամանների աշխատանքի արդյունքի տարբերությունը. echo $str2 echo ${str}2
str="Hola"
echo str2    #str2
echo ${str}2 #Hola2


#2 Արտածել հետեւյալ արտահայտության արժեքը. 52∗4 10
echo $((5 ** 2 * 4 / 10))

#3  Ցուցադրել հետեւյալ հրամանների աշխատանքի արդյունքի տարբերությունը. echo "The balance for user $USER is: $5.00" echo "The balance for user $USER is: \$5.00"
echo "The balance for user $USER is: $5,00" # կտպի։ ,00
echo "The balance for user $USER: \$5,00"   # կտպի: $5,00


#4 Ցուցադրել հետեւյալ հրամանների աշխատանքի արդյունքի տարբերությունը. echo '$USER $((2 + 2)) $(ls)' echo "$USER $((2 + 2)) $(ls)"
echo '$USER $((2 + 2)) $(ls)' # հասկանում է որպես տեքստ
echo "$USER $((2 + 2)) $(ls)" #փակագծի գործողությունը կկատարի


#5 Առանձին տողերում արտածել ընթացիկ դիրեկտորիան եւ այնտեղ առկա տեքստային ֆայլերի քանակը։ Օգտագործել Here document:
current_dir=$(pwd)
num_files=$(ls -l | grep -c "^-")
cat <<EOF
Current directory: $current_dir
Number of files: $num_files
EOF

#6 Գրել 2 թվեր գումարող ֆունկցիա։ Թվերը ֆունկցիային փոխանցել որպես արգումենտներ։
sum_numbers() {
  sum=$(($1 + $2))
  echo "The summary $1 and $2 is equal to $sum"
}

sum_numbers 10 6


#7 Գրել ֆունկցիա, որը որպես արգումենտ կստանա դիրեկտորիայի անվանումը եւ կարտածի այնտեղ առկա ֆայլերի քանակը
count_files() {
  dir_name=$1
  num_files=$(ls -l $dir_name | grep -c "^-")
  echo "Number of files in the directory $dir_name: $num_files"
}

count_files ./


#8 Գրել սկրիպտ, որում նոր ստեղծված ֆայլի համար ստուգել, թե արդյոք այն ունի կարդալու / գրելու / կատարելու թույլտվություն, եւ արտածել համապատասխան հաղորդագրություն։
touch new_file.txt
if [ -e new_file.txt ]; then
  chmod +rwx new_file.txt
  echo "File new_file.txt has been created, and permissions for read, write, and execute are set."
else
  echo "File new_file.txt was not created."
fi


#9 Գրել սկրիպտ, որը կորոշի տրված 2 թվերից մեծագույնը եւ կարտածի
find_max() {
  if [ $1 -gt $2 ]; then
    echo "The largest number is: $1"
  else
    echo "The largest number is: $2"
  fi
}

find_max 29 57

#10 Գրել սկրիպտ, որը կորոշի տրված թիվը զույգ է, թե կենտ։ Արտածել համապատասխան հաղորդագրություն։
check_() {
  if [ $(($1 % 2)) -eq 0 ]; then
    echo "$1 is an even number."
  else
    echo "$1 is an odd number."
  fi
}

check_ 15
check_ 38
